server:  port: 9999# Not working with context path, need to modify the routes if we add#  servlet: #    context-path: /ShoppingGateway

spring:
  application:
    name: ShoppingGateway  zipkin:    base-url: http://localhost:9411/
  cloud:    loadbalancer:      ribbon:        enabled: false
    gateway:
      routes:
      - id: searchservice_route
        uri: lb://SearchService#        uri: http://localhost:2031
        predicates:
        - Path=/SearchService/search/**
      - id: productservice_route
        uri: lb://ProductService#        uri: http://localhost:2032
        predicates:
        - Path=/ProductService/product/**